all:
  children:
    clients:
      hosts:
        client1: {ansible_host: "172.12.50.21"}
        client2: {ansible_host: "172.12.50.22"}
    stations:
      hosts:
        ronny01: {ansible_host: "172.12.50.101"}
        ronny02: {ansible_host: "172.12.50.102"}
        ronny03: {ansible_host: "172.12.50.103"}
        ronny04: {ansible_host: "172.12.50.104"}
        ronny05: {ansible_host: "172.12.50.105"}
        ronny06: {ansible_host: "172.12.50.106"}
        ronny07: {ansible_host: "172.12.50.107"}
        ronny08: {ansible_host: "172.12.50.108"}
  vars:
    ansible_user: "zeus"
    ansible_password: "zeusisdemax"

