---
- name: Install the coredns container on client2
  hosts: client2
  tasks:
    - name: Import the dns_server role
      import_role:
        name: dns_server

# Won't work with NetworkManager
#- name: Configure all devices to use client2 as dns server
#  hosts: all
#  tasks:
#    - name: Import the dns_client role
#      become: true
#      import_role:
#        name: dns_client
