---
- hosts: all
  tasks:
    - name: Set the hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Add a /etc/hosts entry for our hostname
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: '^127\.0\.0\.1[ \t]+localhost'
        line: "127.0.0.1\t{{ inventory_hostname }}"
        owner: root
        group: root
        mode: '0644'
        create: true

    - name: Set timezone to Europe/Brussels
      become: true
      community.general.timezone:
        name: "Europe/Brussels"

    - name: Change the user and root password
      become: true
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ 'zeusisdemax' | password_hash('sha512') }}"
      loop:
        - "{{ ansible_user }}"
        - "root"

    - name: Add the user to the sudo group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: sudo
        append: true

    - name: Allow users to use tcp/udp ports < 1024
      become: true
      ansible.posix.sysctl:
        name: "net.ipv4.ip_unprivileged_port_start"
        value: "1"

    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        install_recommends: false
        name:
          - acl
          - build-essential
          - curl
          - dnsutils
          - git
          - htop
          - iperf3
          - libpq-dev
          - p7zip-full
          - pgcli
          - postgresql-client
          - ranger
          - tmux
          - vim
          - vim-gui-common

    - name: Deploy Prometheus node exporter
      import_role:
        name: prometheus.prometheus.node_exporter # 0.0.0.0:9100
      tags: ["exporter"]

    - name: Add defaults and aliases to .bashrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          export EDITOR=vim
          export PAGER=less

          export HISTSIZE=1000000000
          export HISTFILESIZE=1000000000
          alias nohist="export HISTFILE=/dev/null"

          alias ls="ls --color=tty"
          alias la="ls -lA"
          alias ll="ls -lh"
          alias l="ls -lAh"
          eval "$(dircolors)"

          alias G="grep --color=always"
          alias L="less -S -i"

          alias s="sudo"
          alias se="sudo -e"

          alias v="vim"
          alias sv="sudo vim"

          alias r="ranger"
          alias sr="sudo ranger"

          alias sctl="sudo systemctl"
          alias uctl="systemctl --user"

          alias d="docker"
          alias dc="docker compose"
          alias dcps="docker compose ps -a | less -S"

          alias p="podman"
          alias pc="podman compose"
          alias pcps="podman compose ps -a | less -S"
        state: present
        create: true
    - name: Add defaults to .vimrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.vimrc"
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        block: |
          set nu
          set bri lbr
          set ts=4 sw=4 et
          set ic sc
          set mouse=a
          command W w !sudo tee %
        state: present
        create: true
