---
- hosts: clients
  tasks:
    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        install_recommends: false
        name:
          - default-jdk-headless
          - docker-compose
          - passt
          - podman
          - podman-docker
          - uidmap

    - name: Enable user podman socket
      ansible.builtin.systemd:
        daemon_reload: true
        name: "podman.socket"
        enabled: true
        state: started
        scope: user
      tags: ["services"]

    - name: Import the dbeaver role
      ansible.builtin.import_role:
        name: dbeaver
