---
- name: Checkout the monitoring repository
  ansible.builtin.git:
    repo: "https://github.com/12urenloop/monitoring.git"
    dest: "/home/zeus/monitoring"
    version: "trunk"
  tags: ["monitoring"]

- name: Execute startup script
  ansible.builtin.command:
    chdir: "/home/zeus/monitoring"
    cmd: "bash start.sh config_prod.env"
