---
- name: Install postgresql through apt
  become: true
  ansible.builtin.apt:
    update_cache: true
    install_recommends: false
    name:
      - postgresql
  tags: ["db"]

- name: Ensure the postgresql service is enabled and started
  become: true
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: started
  register: "postgresqlDetails"
  until: 'postgresqlDetails.status.ActiveState == "active"'
  retries: 15
  delay: 2
  tags: ["db"]
- name: Wait for postgres port to come up
  wait_for:
    port: 5432
  tags: ["db"]

- name: 'Create the "{{ ronny_db_user }}" postgres user'
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    login_db: postgres
    name: "{{ ronny_db_user }}"
    password: "{{ ronny_db_password }}"
  tags: ["db"]
- name: 'Create a new postgres database with name "{{ ronny_db }}"'
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ ronny_db }}"
    owner: "{{ ronny_db_user }}"
  tags: ["db"]
- name: 'Grant the "{{ ronny_db_user }} ALL privileges on the "{{ ronny_db }}" postgres database'
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    login_db: "postgres"
    privs: "ALL"
    type: "database"
    roles: "{{ ronny_db_user }}"
    obj: "{{ ronny_db }}"
  tags: ["db"]

- name: Install golang through apt
  become: true
  ansible.builtin.apt:
    update_cache: true
    install_recommends: false
    name:
      - golang
  tags: ["db"]

- name: Checkout the ronny repository
  become: true
  ansible.builtin.git:
    repo: "https://github.com/12urenloop/Ronny-the-station-chef.git"
    dest: "/gonny/"
    version: "main"
  tags: ["gonny"]
- name: Install go dependencies
  become: true
  ansible.builtin.command:
    cmd: go mod download
    chdir: /gonny/
  tags: ["gonny"]
- name: Build gonny binaries
  become: true
  ansible.builtin.command:
    cmd: "env go build -o cmds/{{ item }}/main cmds/{{ item }}/main.go"
    chdir: /gonny/
  loop:
    - collector
    - spreader
  tags: ["gonny"]

- name: Copy gonny systemd files
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - gonny-collector.service
    - gonny-spreader.service
  tags: ["gonny"]
- name: Enable systemd services
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - gonny-collector
    - gonny-spreader
  tags: ["gonny"]

- name: 'Deploy Prometheus exporter for the postgres "{{ ronny_db }}" database'
  vars:
    postgres_exporter_name: "postgresql://{{ ronny_db_user }}:{{ ronny_db_password }}@127.0.0.1/{{ ronny_db }}"
  ansible.builtin.import_role:
    name: prometheus.prometheus.postgres_exporter # 0.0.0.0:9187
  tags: ["exporter"]
